load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_binary(
    name = "background_texture_main",
    srcs = [
        "background_texture_main.cc",
    ],
    deps = [
        "//lib/api:game",
        "//lib/api:level",
    ],
)
