name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: bazel build //...

name: engine-api-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  engine-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: bazel test //lib/api/...

name: engine-internal-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  engine-internal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: bazel test //lib/internal/...
